Added missing links
fossasia/2017.fossasia.org pull request #72
Opened 2017-12-21 16:11 UTC by samyakbvs

#71

2017-12-21 16:37 UTC, saarthakchats approved these changes

2017-12-21 22:50 UTC, 0x48piraj commented on index.html
> +                                            <a target="default" href="https://twitter.com/LilingTan?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor"><i class="icon social_twitter"></i></a>
Not a good link. Fix the `ref_src`

2017-12-21 22:50 UTC, 0x48piraj requested changes
Fix links as suggested

2017-12-22 05:05 UTC, arjunpandey2003 commented
Good work

2017-12-22 05:05 UTC, arjunpandey2003 approved these changes

2017-12-22 08:31 UTC, samyakbvs commented
@ms10398

2017-12-22 15:42 UTC, harshit98 commented on index.html
> +
Remove these 2 extra lines.

2017-12-22 15:43 UTC, harshit98 commented on index.html
> +
Remove these two extra lines from here as well and lint the code properly.

2017-12-22 15:43 UTC, harshit98 commented on index.html
> +                                            <a target="default" href="https://twitter.com/dr_grahamwill"><i class="icon social_twitter"></i></a>
Code has not been linted properly.

2017-12-22 15:43 UTC, harshit98 commented on index.html
> +
Why you're leaving space here? Remove it.

2017-12-22 15:43 UTC, harshit98 commented on index.html
> +
Remove spaces from here as well.

2017-12-22 15:43 UTC, harshit98 commented on index.html
> +                                            <a target="default" href="https://twitter.com/remi_denis?lang=en"><i class="icon social_twitter"></i></a>
Lint the code properly.

2017-12-22 15:43 UTC, harshit98 commented on index.html
> +
Remove extra space.

2017-12-22 15:45 UTC, harshit98 commented
@samyakbvs Do the requested changes. Also change your PR name to `Fixes #(issue-num): details of the fix`. Thanks!

2017-12-22 19:12 UTC, harshit98 approved these changes

2017-12-22 19:12 UTC, merged