Added 8 profile links
fossasia/2017.fossasia.org pull request #73
Opened 2017-12-21 16:36 UTC by saarthakchats

2017-12-21 16:39 UTC, saarthakchats commented
#71

2017-12-21 16:39 UTC, samyakbvs approved these changes

2017-12-21 16:40 UTC, samyakbvs commented
Great work! Saarthak

2017-12-21 22:52 UTC, 0x48piraj commented on index.html
> +												<a href="https://github.com/ppaeps"><i class="icon social_github"></i></a>
Indent well

2017-12-21 22:52 UTC, 0x48piraj requested changes
See the code reviews. Pay attention to indentation.

2017-12-22 07:50 UTC, the-codingninja approved these changes

2017-12-22 07:51 UTC, merged

2017-12-22 22:22 UTC, mariobehling commented
It looks like this PR is on of the PRs that resulted in breaking the site. I have to revert it.