Added 8 Links
fossasia/2017.fossasia.org pull request #75
Opened 2017-12-21 17:14 UTC by arjunpandey2003

2017-12-21 22:55 UTC, 0x48piraj commented on index.html
>  											<a target="default" href="https://www.linkedin.com/in/datacharmer/"><i class="icon social_linkedin"></i></a>
Indentation !

2017-12-21 22:55 UTC, 0x48piraj reviewed
Provide a deploy link.

2017-12-22 05:04 UTC, arjunpandey2003 commented
https://arjunpandey2003.github.io/2017.arjunpfossasia.org/.

2017-12-22 09:34 UTC, STEdirisuriya commented
@arjunpandey2003 please describe your changes

2017-12-22 09:39 UTC, supunTE requested changes

2017-12-22 09:39 UTC, STEdirisuriya commented on index.html
> +                                                                                        <a target="default" href="https://github.com/Orbiter"><i class="icon fa fa-github"></i></a>
Indent

2017-12-22 09:39 UTC, STEdirisuriya commented on index.html
> +                                                                     			<a target="default" href="https://github.com/autonome"><i class="icon fa fa-github"></i></a>
This line already there

2017-12-22 09:39 UTC, STEdirisuriya commented on index.html
> +                                                                     			<a target="default" href="https://github.com/autonome"><i class="icon fa fa-github"></i></a>
See line 656

2017-12-22 09:39 UTC, STEdirisuriya commented on index.html
> +
Remove unwanted spaces

2017-12-22 09:39 UTC, STEdirisuriya commented on index.html
>                                              						<a target="default" href="https://github.com/autonome"><i class="icon fa fa-github"></i></a>
see 654 line.

2017-12-22 09:39 UTC, STEdirisuriya commented on index.html
> +                                            <a target="default" href="https://github.com/autonome"><i class="icon fa fa-github"></i></a>
Indent

2017-12-22 09:43 UTC, supunTE requested changes

2017-12-22 09:43 UTC, STEdirisuriya commented on index.html
>                                              						<a target="default" href="http://github.com/aselle"><i class="icon fa fa-github"></i></a>
This line already there see line 726!

2017-12-22 09:43 UTC, STEdirisuriya commented on index.html
> +
Remove unwanted spaces

2017-12-22 09:43 UTC, STEdirisuriya commented on index.html
>  											<a target="default" href="https://2ndquadrant.com"><i class="icon fa fa-external-link">
This line already there see 764!

2017-12-22 09:49 UTC, supunTE requested changes

2017-12-22 09:49 UTC, STEdirisuriya commented on index.html
> +
Remove unwanted spaces

2017-12-22 09:49 UTC, STEdirisuriya commented on index.html
> +
Remove unwanted spaces

2017-12-22 09:49 UTC, STEdirisuriya commented on index.html
> +			<a target="default" href="https://www.linkedin.com/in/datacharmer/"><i class="icon social_linkedin"></i></a>
indent

2017-12-22 09:49 UTC, STEdirisuriya commented on index.html
> +                                                                                        <a target="default" href="https://github.com/datacharmer"><i class="icon fa fa-github"></i></a>											<a ta
This line already there!

2017-12-22 09:49 UTC, STEdirisuriya commented on index.html
>  											<a target="default" href="https://twitter.com/melvinzhangzy"><i class="icon social_twitter"></i></a>
Indent

2017-12-22 09:49 UTC, STEdirisuriya commented on index.html
>  											<a target="default" href="https://twitter.com/niranjan94"><i class="icon social_twitter"></i></a>
Indent

2017-12-22 09:49 UTC, STEdirisuriya commented on index.html
> +											<a target="default" href="https://yuenhoe.com/"> <a target="default" href="https://github.com/jasonmoofang/"><i class="icon fa fa-github"></i></a>
Indent!

2017-12-22 14:08 UTC, supunTE requested changes
Change those

2017-12-22 14:08 UTC, supunTE commented on index.html
> +                                                                                        <a target="default" href="https://github.com/fweng322"><i class="icon fa fa-github"></i></a>
Indent needed!

2017-12-22 14:08 UTC, supunTE commented on index.html
> +                                                                                        <a target="default" href="http://github.com/aselle"><i class="icon fa fa-github"></i></a>
small indent

2017-12-22 14:09 UTC, STEdirisuriya commented
Please can you squash your commits.

2017-12-22 14:57 UTC, the-codingninja requested changes
Resolve conflicts

2017-12-22 15:02 UTC, arjunpandey2003 commented
Resolved

2017-12-22 15:08 UTC, abishekvashok requested changes

2017-12-22 15:08 UTC, abishekvashok commented on index.html
> +                                                                     			<a target="default" href="https://github.com/autonome"><i class="icon fa fa-github"></i></a>
You got unwanted tabs at the end.

2017-12-22 15:08 UTC, abishekvashok commented on index.html
> +                                                                                        <a target="default" href="http://github.com/aselle"><i class="icon fa fa-github"></i></a>
Same here

2017-12-22 21:16 UTC, vaibhavsingh97 commented
Please resolve conflicts

2017-12-23 03:58 UTC, samyakbvs commented
Great job! @arjunpandey2003

2017-12-23 03:59 UTC, samyakbvs approved these changes

2017-12-23 14:01 UTC, supunTE approved these changes
LGTM! If you merge it and squash it will be excellent.

2017-12-23 16:49 UTC, arjunpandey2003 commented
@mariobehling please review

2017-12-23 16:55 UTC, mariobehling commented
Your test page shows errors. Please check first. Developers are the first testers of their own code. Or if this is not the test page anymore provide a new one, please.

2017-12-23 17:05 UTC, arjunpandey2003 commented
@mariobehling sorry i dont know what a test page is.

2017-12-25 09:48 UTC, nzec reviewed
Merge Conflicts!

2017-12-25 09:54 UTC, closed without merging