Added missing profile links
fossasia/2017.fossasia.org pull request #90
Opened 2017-12-26 15:05 UTC by samyukthacodes

Fixes #89. Please check the reference issue for details. The preview is available at https://samyukthacodes.github.io/2017.fossasia.org/index.html

2017-12-26 17:13 UTC, anshumanv requested changes
Check comments.

2017-12-26 17:13 UTC, anshumanv commented on index.html
> +											<a target="default" href="https://www.facebook.com/melvinzhang?hc_ref=ARQXjNouqW8ylbUiOyAsWzT1c1FcJuAC8pWvXITzr1gOXUKU0OFbjDG5pDgMzi53EWM"><i class="icon social_facebook"></i></a>
Replace - https://www.facebook.com/melvinzhang

2017-12-26 17:13 UTC, anshumanv commented on index.html
> +																								<a target="default" href="https://twitter.com/ddtru"><i class="icon social_twitter"></i></a>
Indent

2017-12-26 17:27 UTC, samyukthacodes commented
@anshumanv Hi. I made the edits you asked for. Could you please check them and see if it's alright?

2017-12-26 17:55 UTC, anshumanv commented on index.html
> +                                                <a target="default" href="https://github.com/andrey-terekhov"><i class="icon fa fa-github"></i></a>
Last indent, thanks for incorporating changes quickly. :smile:

2017-12-27 08:26 UTC, naveentherocker commented
Please remove unwanted lines from the Code

2017-12-27 11:30 UTC, samyukthacodes commented
@anshumanv I've fixed it. 
@naveentherocker Which unwanted lines should i fix?

2017-12-27 20:20 UTC, ParthS007 requested changes

2017-12-27 20:20 UTC, ParthS007 commented on index.html
> +												<a target="default" href="https://github.com/shimanokaze"><i class="icon fa fa-github"></i></a>
@samyukthacodes Please add a link only once, Remove one GitHub link

2017-12-28 00:24 UTC, isuruAb commented on index.html
> +												<a target="default" href="https://github.com/shimanokaze"><i class="icon fa fa-github"></i></a>
please remove repeated lines

2017-12-28 03:45 UTC, samyukthacodes commented
@ParthS007 @isuruAb Those changes were not made by me. They were already there. I thought of fixing them in a seperate pull request. If you want i can fix them as well.

2017-12-28 12:11 UTC, samyukthacodes commented
@ParthS007 @isuruAb I've made the changes you requested. Hope everything is alright now.

2017-12-28 16:29 UTC, samyukthacodes commented
@isuruAb @ParthS007  @anshumanv  I've only two days remaining for this task which is a part of google code-in. If everything is fine could you please approve and merge this PR?

2017-12-28 16:46 UTC, ParthS007 approved these changes

2017-12-29 02:42 UTC, yashLadha commented
Please resolve the merge conflicts.

2017-12-29 05:03 UTC, samyukthacodes commented
@yashLadha Resolved

2017-12-29 14:10 UTC, the-codingninja approved these changes

2017-12-29 14:12 UTC, saurabhjn76 approved these changes

2017-12-29 16:40 UTC, NaviRocker approved these changes
LGTM

2017-12-30 08:55 UTC, anshumanv approved these changes

2017-12-30 08:56 UTC, merged